title: YU Wang # your name (or website title) here
logo: "C:\\Users\\75925\\OneDrive\\Desktop\\nba.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br>Hi! My name is Yu Wang <br>
  Second description 
  <br> I'm a Upenn student<br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
